### ISSUE TITLE
Classes for kramdown HTML don't match rougify stylesheet classes

### ISSUE THREAD

**Issue by choldgraf** [jneen/rouge#1005]
Apologies if this is a stupid question, but I can't figure out how to get my rougify CSS classes to match those that are output from Kramdown. I'm using Jekyll with the following Jekyll config:

```
...
# Conversion
markdown: kramdown
lsi: false
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
...
```

And I've generated a rouge CSS sheet with

```
rougify style github
```

However, when I look at the classes of the rendered HTML, they are *slightly* off from the rouge CSS so that the rules aren't applied. E.g, the HTML has classes like `span.p` while this rule doesn't exist in the rougify CSS. Sometimes the HTML has a class w/ one letter like `span.n` while the Rouge CSS has two-letter classes like `.nb`, `.nc`, etc.

Anyone have an idea why there is this discrepancy?
